server:
  port: ${SERVER_PORT:8083}

spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: media-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.buy01.events
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/buy01_media}
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:4fd8a6c3b92f4a8c9c6b8a1f2e3d4c5f6a7b8c9d}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.clients.consumer.internals: ERROR
    org.springframework.kafka: WARN
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    org.springframework.cloud.netflix.eureka: WARN
